stages:
  - build
  - test
  - publish

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file:
      - '.gitlab-ci-github-status-updates.yml'
      - '.gitlab-ci-check-golang-lint.yml'
      - '.gitlab-ci-check-golang-unittests.yml'
      - '.gitlab-ci-check-commits.yml'
      - '.gitlab-ci-check-license.yml'

# Test that we can build with the golang version of the oldest supported yocto LTS release
test:backwards-compatibility:
  image: golang:1.17.13-bullseye
  needs: []
  script:
    - go build
