stages:
  - build
  - test
  - publish

include:
  - project: Northern.tech/Mender/mendertesting
    file:
      - qa-common/runner.yml
      - qa-common/retry.yml
  - project: 'Northern.tech/Mender/mendertesting'
    file:
      - '.gitlab-ci-github-status-updates.yml'
      - '.gitlab-ci-check-golang-lint.yml'
      - '.gitlab-ci-check-golang-unittests.yml'
      - '.gitlab-ci-check-license.yml'
  - component: gitlab.com/Northern.tech/Mender/mendertesting/commit-lint@master
  - component: gitlab.com/Northern.tech/Mender/mendertesting/backwards-compatible-yocto@master

default:
  tags: !reference [.qa-common-default-runner, tags]
  retry: !reference [.qa-common-default-retry, retry]
